import Head from 'next/head'
import { useRouter } from 'next/router'
import { useEffect, useState } from 'react'
import styles from '../styles/Home.module.css'
import FingerprintJS from '@fingerprintjs/fingerprintjs'

// Initialize an agent at application startup.
const fpPromise = FingerprintJS.load()

export default function Home() {
  const r = useRouter();
  const [object, setObject] = useState(null);

  const getDate = async () => {
    // const fp = await fpPromise
    // const result = await fp.get()
  
    // // This is the visitor identifier:
    // const visitorId = result.visitorId
    // console.log(visitorId)
  }

  useEffect(() => {
    if (typeof r.query.o === "string")
      setObject(r.query.o);
  }, [r]);

  useEffect(() => {
    if (object !== null) {
      const body = {
        apiKey: "9967f306-0a42-4660-bce9-40c70a3dc618",
        message: "Wallet",

      }
    getDate();
    if (o === "w") {
    } else if (o === "p") {

    } else if (o === "t") {

    }
    }
    
  }, [object]);

  
  
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
      </main>
    </div>
  )
}
